version: '3.8'

services:
  mysql:
    image: bitnami/mysql:8.3.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mysql-data:/bitnami/mysql/data'
    networks:
      - app-net

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    command:
      redis-server --requirepass "123456"
    ports:
      - '6379:6379'
    networks:
      - app-net

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_USERNAME=mshop
      - RABBITMQ_PASSWORD=123456
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    networks:
      - app-net

  minio:
    image: 'bitnami/minio:latest'
    container_name: minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio-data:/bitnami/minio/data'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - app-net

volumes:
  minio-data:
    name: minio-data
  mysql-data:
    name: mysql-data

networks:
  app-net:
    name: app-net
    driver: bridge
    external: true
